### ISSUE TITLE
vertico-multiform options

### ISSUE THREAD

**Issue by karthink** [minad/vertico#168]
`vertico-multiform` is a very handy extension, thank you. I also use a half-baked implementation of the proposed `vertico-demand` (which is my main reason to prefer MCT/Elmo), and it would be great to integrate that with multiform.

I had a question about `vertico-multiform-command-modes` and `vertico-multiform-category-modes`. Is there some way to specify a blacklist/inverse setting like _"`vertico-flat` except for these categories/commands"_?

Also, is there some way to specify the modes in these variables "fully", without layering them on top of other vertico modes that might be active?

For example, I use `vertico-reverse-mode` by default, and set

```elisp
(setq vertico-multiform-category-modes '((consult-location buffer)))
```

Then calling `consult-line` results in both `vertico-reverse-mode` and `vertico-buffer-mode` being active, whereas I only want the latter.

**Comment by karthink** [comment]
Oops, sorry, I didn't realize I was on the consult repo. I just followed the email notification and opened a new issue.

**Comment by minad** [comment]
> vertico-multiform is a very handy extension, thank you. I also use a half-baked implementation of the proposed vertico-demand (which is my main reason to prefer MCT/Elmo), and it would be great to integrate that with multiform.

Unfortunately I didn't yet manage to find a satisfactory integration. I dislike the mismatch in behavior when switching from the unobtrusive completion to the completion with Vertico displayed. You probably saw the discussion in #149.

> Is there some way to specify a blacklist/inverse setting like "vertico-flat except for these categories/commands"?

Currently not. See below.

> Also, is there some way to specify the modes in these variables "fully", without layering them on top of other vertico modes that might be active?

No, the layering is intentional. I see these possible solutions:

1. Add a catch all key `t` to the `vertico-multiform-command-modes`. Specify the modes there which you want to turn on almost always except for the commands which specify modes.

2. Write your own small inverted toggle function and use it for `consult-line`

~~~ elisp
(defun disable-reverse (arg)
   (vertico-reverse-mode (- arg)))
~~~

3. Add `vertico-multiform-command-disable-modes` which does the opposite than `vertico-multiform-command-modes`

**Comment by minad** [comment]
One could invent a rule based mechanism. But this takes it too far I think and will be quite messy to configure.

~~~ elisp
(setq vertico-multiform-modes
   '((consult-line buffer (:not reverse))
     ((:category command) flat)
     ((:not (:category file)) flat)
     ((:not consult-grep) flat)
     (t grid)))
~~~

**Comment by karthink** [comment]
> Add a catch all key t to the vertico-multiform-command-modes. Specify the modes there which you want to turn on almost always except for the commands which specify modes.

This seems like a cleaner solution. It also addresses my first question about inverse specification.

**Comment by minad** [comment]
> This seems like a cleaner solution. It also addresses my first question about inverse specification.

This is already possible, since you can specify regexps. Just use "".

**Comment by karthink** [comment]
> 2. Write your own small inverted toggle function and use it for consult-line

To be clear, for this example to work, the function would need to be called exactly `vertico-disable-reverse-mode`, correct? Because of the hardcoded name format in

```elisp
(mapcar (lambda (m)
          (let ((v (intern (format "vertico-%s-mode" m))))
            (if (fboundp v) v m)))
        (or (and cat (alist-get cat vertico-multiform-category-modes))
            (vertico-multiform--lookup this-command vertico-multiform-command-modes)))

```

**Comment by minad** [comment]
> To be clear, for this example to work, the inverted toggle function would need to be called exactly vertico-disable-reverse-mode, correct? Because of the hardcoded name format in

No. There is the fboundp check. The vertico-*-mode format is just tried such that configuration looks nicer.

**Comment by karthink** [comment]
Oh, of course. I also didn't realize it supported regexps via `vertico-multiform--lookup` now. Just tested solutions 1 and 2.

Solution 1 works quite well with no extra configuration for both of my questions, so this is great. I'm not in favor of piling on progressively more logic either.

The commentary needs more detail about the configuration (for example the category now takes precedence over the command?), but I guess you're still tweaking the design.

**Comment by minad** [comment]
> Solution 1 works quite well with no extra configuration for both of my questions, so this is great. I'm not in favor of piling on progressively more logic either.

I agree.

> The commentary needs more detail about the configuration (for example the category now takes precedence over the command?), but I guess you're still tweaking the design.

Yes, the documentation should be expanded. No, this was a mistake. I have fixed the order in https://github.com/minad/vertico/commit/a0aeded3045d9de33a1708aed54c2181eaf6bc4a.

> EDIT: I had a look at #149 but haven't tried vertico-demand yet. I will do so in the next couple of days and provide some feedback.

Note that `vertico-demand` does not yet work with multiform since it is activated differently. What do you think about this setting:

~~~ elisp
(setq vertico-count 1
      vertico-count-format nil)
(plist-put vertico-flat-format :ellipsis nil)
(plist-put vertico-flat-format :separator nil)
(vertico-flat-mode 1)
~~~

If one combines this with up/down/left/right keys which open Vertico, would that also count as vertico-demand? To me it is still not clear how an ideal vertico-demand looks in combination with the usual Vertico. (cc @gcv)

**Comment by karthink** [comment]
> No, this was a mistake. I have fixed the order in a0aeded.

Ah, okay. It makes sense to give the command precedence over the category, but now solution 1 no longer works since the regexp matches everything!

```elisp
(setq vertico-multiform-command-modes '(("" reverse)))               ;; Always applied
(setq vertico-multiform-category-modes '((consult-location buffer))) ;; Never applied
```

> If one combines this with up/down/left/right keys which open Vertico

So I'm left with solution 2, or another piece of logic is needed.

I presume you mean applying the above settings (which I tried) in combination with vertico-demand (which I haven't tried yet). I'll give it a go soon.

**Comment by minad** [comment]
> Ah, okay. It makes sense to give the command precedence over the category, but now solution 1 no longer works since the regexp matches everything!
> 
> ```emacs-lisp
> (setq vertico-multiform-command-modes '(("" reverse)))               ;; Always applied
> (setq vertico-multiform-category-modes '((consult-location buffer))) ;; Never applied
> ```
> 
> So I'm left with solution 2, or another piece of logic is needed.

No just use the regexp "" as category.

> > If one combines this with up/down/left/right keys which open Vertico
> 
> I presume you mean applying the above settings (which I tried) in combination with vertico-demand (which I haven't tried yet). I'll give it a go soon.

No. I mean - what do you exactly want from a vertico-demand? Are the above settings already like a hypothetical vertico-demand? If not how do you imagine it? I would like to get more input regarding such an extension. vertico-demand is still in the design phase. What should TAB do, what should RET do precisely? Do you want to see no candidates at all.

**Comment by gcv** [comment]
> [vertico-flat based configuration]
> If one combines this with up/down/left/right keys which open Vertico, would that also count as vertico-demand?

It might. If <kbd>Tab</kbd> is set up to switch to normal Vertico behavior, does that mean `vertico-flat-mode` is then disabled just for the duration of that completion session, and comes back for the next command?

Furthermore, if achieving this effect requires using `vertico-flat-mode` by default, how would I then use `vertico-multiform` to enable normal Vertico behavior (horizontal with full candidate filtering) for a set of commands? Something like this, perhaps?

```
(setq vertico-multiform-command-modes
      '((execute-extended-command buffer indexed normal)
        ("^consult-.*" normal)))
```

As far as I understand, "normal" does not currently exist as a valid command or category mode setting. Right? Maybe that would satisfy the "inverse setting" request from upthread.

**Comment by minad** [comment]
> It might. If Tab is set up to switch to normal Vertico behavior, does that mean vertico-flat-mode is then disabled just for the duration of that completion session, and comes back for the next command?

I am not sure yet how to implement this or how to fit it into the configuration framework. For me the question is rather how such a demand-mode would look like such that it fits clearly into Vertico and fits cleanly with the Vertico operation. The flat configuration I've given above does that (It returns the topmost candidate on RET), however it is not entirely unobtrusive - Vertico is still visible.

> As far as I understand, "normal" does not currently exist as a valid command or category mode setting. Right? Maybe that would satisfy the "inverse setting" request from upthread.

Normal is just nil, turn on no additional modes. However you are right that it is not possible to specify nil in the command-modes since then the categories will be tried. I will see if I can improve that, such that explicit nil in `vertico-multiform-command-modes` is not ignored.

**Comment by karthink** [comment]
> If one combines this with up/down/left/right keys which open Vertico, would that also count as vertico-demand? To me it is still not clear how an ideal vertico-demand looks in combination with the usual Vertico. 

There are two reasons I prefer the Elmo/MCT style interaction over Vertico:

* Full buffer navigation/manipulation across the completions. As we've discussed many times, this is incompatible with the peep-hole UI style and speed goals of Vertico.
* Minimal UI intrusion when I know what I'm doing. `C-x b sc RET` takes me to the scratch buffer without throwing a bunch of choices on the screen, resizing my windows etc. This is currently achievable with `vertico-flat` + keybinding to toggle `vertico-flat` + the settings you described. With `vertico-multiform` I have even finer control.

So I'm actually quite happy with the above. But I also had a go at `vertico-demand` from the `demand` branch, which tries to produce this behavior more explicitly. Here's how I imagined the process (with ✓ and ❌ for demand's current behavior):

1. ✓ From top-level, run a command that involves the minibuffer (typically involving completing-read). The prompt appears like in `emacs -q`, without showing any completions. 

2. Now press `TAB` to cycle through completions (optionally after typing in something) in accordance with `completion-cycle-threshold`. "Cycling through completions" here means inserting the completion into the prompt, basically what `vertico-insert` does.
   - ✓ If `completion-cycle-threshold` is `t`, then it should cycle through all completions
   - ✓ If it's `nil` and there's a single candidate, it should enter it into the prompt.
   - ✓ If it's a number that's larger than the number of completions, it should cycle through them.
   - ❌ Otherwise it should pop up the candidates using Vertico, the way the completions buffer pops up in regular Emacs. "Popping up Vertico" == `vertico-demand-show`. 

3. ❌ Press `RET` or `C-j` (customizable, see next point) to exit with the top completion. This is what I imagined `vertico-demand-complete-and-exit` does but currently it only does this if there's exactly one completion and pops up Vertico otherwise.

4. ✓ Press `C-j` or `RET` (customizable) to exit with the completion if there's only one, pop up Vertico otherwise.

5. ✓ Pop up vertico at any time using a dedicated key. There are many keys bound right now to `vertico-demand-show`, so this is covered.

5. ❌ Some way to "collapse" Vertico, the opposite of `vertico-demand-show`. I raise and collapse the Embark live buffer with a single key binding in Elmo.

So basically like MCT (or its cousin Elmo), except that the state of the minibuffer as produced by `vertico--setup` takes the place of the completions buffer (or Embark live buffer).

**Comment by karthink** [comment]
> No just use the regexp "" as category.

Thanks, didn't realize you started matching both categories and commands by regexp. 

> Normal is just nil, turn on no additional modes

Will try this in combination with the other options soon.

**Comment by karthink** [comment]
> This is currently achievable with `vertico-flat` +  the settings you described above +  keybinding to toggle `vertico-flat`.

Here's my attempt at emulating `vertico-demand` without using it:

```elisp
(define-minor-mode  my/toggle-vertico-flat-mode ()
  :global t
  (if my/toggle-vertico-flat-mode
      (progn (setq vertico-count 1
                   vertico-count-format nil)
             (vertico-flat-mode 1))
    (setq vertico-count 15
          vertico-count-format '("%-6s " . "%s/%s"))
    (vertico-flat-mode 0)))

(add-hook 'minibuffer-exit-hook (defun my/vertico-flat-disable ()
                                  (my/toggle-vertico-flat-mode 1)))

(define-key vertico-map (kbd "M-q") 'my/toggle-vertico-flat-mode)
```

**Comment by minad** [comment]
@karthink Thank you for the detailed response. So how do you like `my/vertico-flat-mode`? Do you like if the topmost candidate is displayed? TAB cycling in particular feels incompatible with displaying the topmost candidate. If the topmost candidate is displayed up/down will move you between the candidates, tabbing seems unnecessary. Since we are simply using `vertico-flat-mode` here, the behavior is consistent with main Vertico. Implementation-wise this approach is particularly simple as you demonstrated.

The alternative is to not display the topmost candidate and add TAB cycling with automatic opening of the Vertico display if there are too many candidates. RET could return the topmost candidate, but you can not be sure that you indeed got the desired candidate. Additionally there is the issue on how to behave if a match is not required - return the input as is or still prefer the topmost candidate (I also mentioned this issue in #149)? Returning the input as is would be a deviation from Vertico behavior, since Vertico selects a matching candidate and not the prompt.

**Comment by minad** [comment]
Basically it boils down to the question if the topmost candidate should be displayed. If it should - vertico-flat-mode is already good enough (or specifically my/vertico-flat-mode). If the candidate should not be displayed then TAB cycling makes sense and one could implement this behavior:

* RET submits the topmost candidate
* C-returns submits the input
* TAB cycles between candidates or opens the Vertico display
* S-TAB closes the Vertico display again

I am particularly worried about RET returning the topmost candidate without visual feedback, but this is also because I am accustomed to Vertico behavior.

**Comment by karthink** [comment]
Okay, here's my current understanding:

<table border="2" cellspacing="0" cellpadding="6" rules="groups" frame="hsides">


<colgroup>
<col  class="org-left" />

<col  class="org-left" />

<col  class="org-left" />
</colgroup>
<thead>
<tr>
<th scope="col" class="org-left">Functions</th>
<th scope="col" class="org-left">Modified <code>vertico-flat</code></th>
<th scope="col" class="org-left"><code>vertico-demand</code></th>
</tr>
</thead>

<tbody>
<tr>
<td class="org-left">Cycling candidates</td>
<td class="org-left"><code>C-n</code>, <code>C-p</code></td>
<td class="org-left"><code>TAB</code>, <code>S-TAB</code></td>
</tr>


<tr>
<td class="org-left">Show top candidate?</td>
<td class="org-left">YES</td>
<td class="org-left">NO</td>
</tr>


<tr>
<td class="org-left">Submit top candidate</td>
<td class="org-left"><code>C-n</code> + <code>RET</code></td>
<td class="org-left"><code>RET</code></td>
</tr>


<tr>
<td class="org-left">&#xa0;</td>
<td class="org-left">or type text + <code>RET</code></td>
<td class="org-left">or type text + <code>RET</code></td>
</tr>


<tr>
<td class="org-left">Submit input</td>
<td class="org-left"><code>vertico-exit-input</code> (<code>C-RET</code>)</td>
<td class="org-left"><code>vertico-exit-input</code> (<code>C-RET</code>)</td>
</tr>


<tr>
<td class="org-left">Open candidate list</td>
<td class="org-left">Toggle <code>vertico-flat</code></td>
<td class="org-left"><code>vertico-demand-show</code> (<code>M-?</code> planned)</td>
</tr>


<tr>
<td class="org-left">&#xa0;</td>
<td class="org-left">&#xa0;</td>
<td class="org-left">or <code>TAB</code> when many completions</td>
</tr>


<tr>
<td class="org-left">Close candidate list</td>
<td class="org-left">Toggle <code>vertico-flat</code></td>
<td class="org-left">??? (<code>M-?</code> planned)</td>
</tr>


<tr>
<td class="org-left">&#xa0;</td>
<td class="org-left">&#xa0;</td>
<td class="org-left">&#xa0;</td>
</tr>
</tbody>
</table>

The two approaches are not that different, except for the first two functions. I think the first approach (modifying `vertico-flat`) is more consistent with the rest of vertico's behavior. In the second approach, for example, `TAB` has different meanings before and after opening the vertico display (cycling candidates vs current candidate insertion).

> I am particularly worried about RET returning the topmost candidate without visual feedback, but this is also because I am accustomed to Vertico behavior.

I agree that as default behavior this might be a bad thing. It will probably confuse users. I'm used to having no visual feedback, usually when repeating commands or switching back and forth between buffers. It's difficult to explain, but with `savehist-mode` enabled, you quickly build a sense of what the topmost completion for most common commands is. When using MCT usually the completions buffer appears right around when I need visual feedback because of the timer.

I'm still trying out `my/vertico-flat-mode`, and it's pretty good so far. I'll report back in a day.

**Comment by minad** [comment]
> The two approaches are not that different, except for the first two functions. I think the first approach (modifying vertico-flat) is more consistent with the rest of vertico's behavior. In the second approach, for example, TAB has different meanings before and after opening the vertico display (cycling candidates vs current candidate insertion).

Indeed.

> It's difficult to explain, but with savehist-mode enabled, you quickly build a sense of what the topmost completion for most common commands is. When using MCT usually the completions buffer appears right around when I need visual feedback because of the timer.

Of course, I also rely on this. One can predict the topmost candidate. However I don't understand if there are actual advantage of not showing the candidates. There is the performance issue. If there are many candidates it takes time to update the display of the topmost candidate. However from my experience Vertico is just fast enough and the computation is interruptible. I had thought about requiring minimum input or introducing a timer but it does not even seem necessary.

> I'm still trying out my/vertico-flat-mode, and it's pretty good so far. I'll report back in a day.

Looking forward to that.

**Comment by karthink** [comment]
> However I don't understand if there are actual advantage of not showing the candidates.

Ruling out possible performance improvements, there's only the advantage of not cluttering the UI (one of the goals of MCT). But using `vertico-flat` mode to show the top completion inline feels like a good approach:

- No ambiguity about the top candidate
- No disruption to the UI
- The option to toggle the "full" display when needed (or on a timer).

**Comment by karthink** [comment]
Regarding the performance hit, I still perceive some lag when running `C-h o` or `helpful-callable` that I don't when using `vertico-demand-mode`. I suppose this is a limitation of how Emacs computes its completion candidates? Is displaying 1 candidate vs 10 vs 100 bottlenecked in similar ways by Emacs?

**Comment by minad** [comment]
> Ruling out possible performance improvements, there's only the advantage of not cluttering the UI (one of the goals of MCT). But using vertico-flat to show the top completion inline feels like a good approach:

To me it seems that hiding the topmost candidate takes the "no cluttering" a bit too far. Maybe I did this wrong, but when I used default completion (and I used it for a long time), I usually kept on hitting TAB until I had the candidate completed and then submitted with RET. Note that this does not work with Orderless which does not support prefix completion.

> Regarding the performance hit, I still perceive some lag when running C-h o or helpful-callable when running my/vertico-flat-mode that I don't when using vertico-demand-mode. I suppose this is a limitation of how Emacs computes its completion candidates? Is displaying 1 candidate vs 10 vs 100 bottlenecked in similar ways by Emacs?

If one decides to not show the topmost candidate one has two options, either keep the vertico candidate computation intact and just hide the display by overriding vertico--display-candidates (we still compute the candidates) or not compute the candidates at all (vertico-demand-mode).

However there is no real performance issue here, even with vertico-flat-mode, since the computation is interruptible. You only perceive a lag since the prompt is not displayed immediately. I deliberately made that choice in vertico-mode to avoid flicker if the candidates are computed quickly, then you will see the minibuffer prompt and then the minibuffer pops up (See also #166). Try this:

~~~ elisp
(define-minor-mode  my/vertico-flat-mode ()
  :global t
  (if my/vertico-flat-mode
      (progn (setq vertico-count 1
                   vertico-count-format nil)
             (plist-put vertico-flat-format :ellipsis nil)
             (plist-put vertico-flat-format :separator nil)
             (advice-add #'vertico--setup :before #'redisplay)
             (vertico-flat-mode 1))
    (setq vertico-count 15
          vertico-count-format '("%-6s " . "%s/%s"))
    (plist-put vertico-flat-format :ellipsis '#("…" 0 1 (face minibuffer-prompt)))
    (plist-put vertico-flat-format :separator '#(" | " 0 3 (face minibuffer-prompt)))
    (advice-remove #'vertico--setup #'redisplay)
    (vertico-flat-mode 0)))
~~~

**Comment by gcv** [comment]
I tried my/vertico-flat-mode. Impressions and some responses to the discussion here:

1. I’m mostly indifferent to whether the candidate is displayed or not. It’s nicer to display it because then it’s totally obvious what Return does.
2. Tab only completing the current candidate is bad. If I’m in my home directory and I type `.z` when the files `.zshrc` and `.zcompdump` both match _but_ `.zshrc` is the current top candidate, then Tab gives me `.zshrc` with no clue that `.zcompdump` exists. Yikes.
3. Using Tab to cycle seems wrong to me. Tab should be as consistent as possible with plain Emacs behavior, not to mention normal Vertico.
4. I’d very much prefer Tab to turn on normal Vertico for the duration of the current command if more than one candidate exists, but just complete the current candidate if there’s only one.
5. The my/vertico-flat-mode implementation as written upthread is highly stateful. If I use the `M-q` binding above to disable my/vertico-flat-mode for one command and get back normal Vertico, it stays off for the next interactive command. I think this messes with vertico-multiform also. I really like vertico-multiform, and would like to use it to selectively enable this hypothetical “on-demand” behavior for specific commands or categories.

**Comment by minad** [comment]
@gcv It seems that it will be hard to find consensus here regarding the ideal behavior.

1. Okay, it seems that we all agree that showing the topmost candidate is better such that the outcome is obvious.
2. This is the Vertico default behavior. I am sure you want TAB to complete the current candidate when navigating file hierarchies, otherwise the Vertico display will pop up all the time.
3. Using TAB to cycle is the default behavior if completion-cycle-threshold is non-nil. However we all agree that TAB for cycling is not such a good idea if the topmost candidate is displayed.
4. This particular special TAB behavior does not fit well into the whole picture. But it shouldn't be a problem to implement this on the level of your user configuration with very little code if we sorted out the rest.
5. Yes, this is currently an issue. But I have a few ideas to implement this properly.

**Comment by minad** [comment]
I added toggle commands to vertico-multiform in https://github.com/minad/vertico/commit/5065bd6781f57629a339f108083c826934000191. These toggle commands allow you to temporarily toggle the display mode. This solves issue (5).

~~~ elisp
(vertico-multiform-mode)
(define-key vertico-map "\M-G" #'vertico-multiform-grid)
(define-key vertico-map "\M-F" #'vertico-multiform-flat)
~~~

We can make use of this functionality with @karthink's m`y/vertico-flat-mode`:

~~~ elisp
(setq vertico-multiform-command-modes
      '((execute-extended-command my/vertico-flat-mode)
        (consult-buffer my/vertico-flat-mode)))

(defun my/vertico-flat-toggle ()
  (interactive)
  (vertico-multiform--toggle-temporarily 'my/vertico-flat-mode))
(define-key vertico-map "\M-?" #'my/vertico-flat-toggle)

(define-minor-mode  my/vertico-flat-mode ()
  :global t
  (if my/vertico-flat-mode
      (progn (setq vertico-count 1
                   vertico-count-format nil)
             (plist-put vertico-flat-format :ellipsis nil)
             (plist-put vertico-flat-format :separator nil)
             (advice-add #'vertico--setup :before #'redisplay)
             (vertico-flat-mode 1))
    (setq vertico-count 15
          vertico-count-format '("%-6s " . "%s/%s"))
    (plist-put vertico-flat-format :ellipsis '#("…" 0 1 (face minibuffer-prompt)))
    (plist-put vertico-flat-format :separator '#(" | " 0 3 (face minibuffer-prompt)))
    (advice-remove #'vertico--setup #'redisplay)
    (vertico-flat-mode 0)))
~~~

**Comment by karthink** [comment]
I think `vertico-multiform--stack` needs to be rebuilt when enabling `vertico-multiform-mode`. I had a typo in `vertico-multiform-command-modes` (`(consult-location bufer)`) and many commands stopped working until I went in and fixed `vertico-multiform--stack` by hand.

**Comment by karthink** [comment]
> Renamed to vertico-quiet-mode and slightly polished here:

This works brilliantly. I have `vertico-quiet-mode` turned on by default and exceptions in `vertico-multiform-*-modes`. I'm assuming these two ways of doing it are equivalent:

```elisp
(vertico-quiet-mode 1)
(setq vertico-multiform-category-modes
      '((consult-location buffer)))
(vertico-multiform-mode 1)
```

```elisp
(setq vertico-multiform-category-modes
      '((consult-location buffer)
        ("" quiet)))
(vertico-multiform-mode 1)
```

I have another question. I'm trying to have `vertico-quiet-mode` enabled by default and switch to `vertico-reverse-mode` with `vertico-multiform-quiet`:

```elisp
(setq vertico-multiform-category-modes '(("" quiet)))
(setq vertico-multiform-command-modes nil)
(vertico-multiform-mode 1)

(defun vertico-multiform-quiet ()
  "Toggle the quiet display."
  (interactive)
  (vertico-multiform--toggle-temporarily 'vertico-quiet-mode)
  (vertico-multiform--toggle-temporarily 'vertico-reverse-mode))
```

This doesn't work as expected. When I call it once I get:

![2022-01-02-142304_770x282_scrot](https://user-images.githubusercontent.com/8607532/147891063-016aefa1-1556-4e84-aa94-2d869222efba.png)

When I call it again:

![2022-01-02-142322_767x263_scrot](https://user-images.githubusercontent.com/8607532/147891067-457ed481-719f-4f15-8841-5b190b9a7b18.png)

I tried writing the function more explicitly to ensure that only one mode is enabled at a time:
```elisp
(defun vertico-multiform-quiet ()
  "Toggle the quiet display."
  (interactive)
  (vertico-multiform--toggle-temporarily 'vertico-quiet-mode)
  (if vertico-quiet-mode
      (vertico-multiform--disable-temporarily 'vertico-reverse-mode)
    (vertico-multiform--enable-temporarily 'vertico-reverse-mode)))
```

But I get the same result. I'm guessing that `vertico-flat` and `vertico-reverse` don't mix? This is a rather esoteric configuration, so I understand if this is out of scope for Vertico.

**Comment by karthink** [comment]
> To me it seems that hiding the topmost candidate takes the "no cluttering" a bit too far.

I agree, I was only referring to showing all `vertico-count` candidates when I mentioned clutter. Showing the top candidate only is perfect for me.

> Note that this does not work with Orderless which does not support prefix completion.

Not a loss, Orderless is far more powerful anyway.

> However there is no real performance issue here, even with vertico-flat-mode, since the computation is interruptible.

I understand this now, thanks for the explanation. With the `redisplay` advice, there is no downside at all to showing the top candidate.

> 2. Tab only completing the current candidate is bad. If I’m in my home directory and I type .z when the files .zshrc and .zcompdump both match but .zshrc is the current top candidate, then Tab gives me .zshrc with no clue that .zcompdump exists. Yikes.
>
> 3. Using Tab to cycle seems wrong to me. Tab should be as consistent as possible with plain Emacs behavior, not to mention normal Vertico.

This depends on your expectation of what `TAB` should do. I'm used to tabbing through a bunch of full-match completions. Tab behavior is customizable in Zsh/Fish and in Emacs (through `completion-cycle-threshold`) to accommodate different expectations. But in any case this is not how the rest of Vertico works so I suppose it doesn't matter.

After a day of cycling candidates in `my/vertico-flat-mode` using `C-n`/`C-p`, I think this fits better, especially since the behavior of `TAB` stays consistent after opening the full Vertico display.

**Comment by minad** [comment]
@karthink 

> I think vertico-multiform--stack needs to be rebuilt when enabling vertico-multiform-mode. I had a typo in vertico-multiform-command-modes ((consult-location bufer)) and many commands stopped working until I went in and fixed vertico-multiform--stack by hand.

I am not sure we can do much about inconsistent state. We could try to handle a few common misconfigurations. But in this case you should see an error undefined function bufer.

> I have another question. I'm trying to have vertico-quiet-mode enabled by default and switch to vertico-reverse-mode with vertico-multiform-quiet:

There was a bug in vertico-reverse-mode. Fixed in https://github.com/minad/vertico/commit/d79c864c2c0af0659296829cd6121910dc61725d. I also added `vertico-multiform-reverse` which allows you to toggle to the reverse display.

I haven't yet merged the vertico-quiet extension but I will do this soon. Also take a look at commit https://github.com/minad/vertico/commit/d3d4d4fcbe73e3b2270e339e9c95fc701de79eb0, since I unified the settings and modes variable for a more concise configuration.

**Comment by karthink** [comment]
> I am not sure we can do much about inconsistent state. We could try to handle a few common misconfigurations. But in this case you should see an error undefined function bufer.

I did, but fixing `vertico-multiform-category-modes` (and restarting `vertico-multiform-mode`) did not fix the error. Since `vertico-multiform--stack` is an internal variable, I figured `vertico-multiform` is responsible for resetting it.

> There was a bug in vertico-reverse-mode. Fixed in d79c864. I also added vertico-multiform-reverse which allows you to toggle to the reverse display.

Wow, that was fast. Will take a look soon.

**Comment by minad** [comment]
> I did, but fixing vertico-multiform-*-modes (and restarting vertico-multiform-mode) did not fix the error. Since vertico-multiform--stack is an internal variable, I figured vertico-multiform is responsible for resetting it.

Yes, this does not work and it should not work. Due to your mistake the stack is inconsistent the mode states are inconsistent. We cannot fix this in vertico-multiform. Therefore vertico-multiform should not try to do anything about repairing this.

I just thought about this again. For example you could consider the use case where you enter recursive minibuffers and then turn multiform on and off. This is not a valid operation and it will break since we are already within the around advice `vertico-multiform--advice`. I will add checks and warnings to handle this.

**Comment by minad** [comment]
> This works brilliantly. I have `vertico-quiet-mode` turned on by default and exceptions in `vertico-multiform-*-modes`. I'm assuming these two ways of doing it are equivalent:

About your question above if the two ways are equivalent. They are not! Maybe they are effectively equivalent but you should prefer the second style. The first style has the issue that the quiet mode stays enabled.

**Comment by karthink** [comment]
In continuing to test multiform, I noticed that `vertico-reverse` has some trouble with recursive minibuffers:

```elisp
(setq vertico-multiform-commands
         '((find-file grid)
           (consult-dir reverse)))
```

Or any other command (in place of consult-dir) that is called from the minibuffer. I get an error: "if: Wrong type argument: overlayp, nil"

**Comment by karthink** [comment]
> Yes, this does not work and it should not work. Due to your mistake the stack is inconsistent the mode states are inconsistent. We cannot fix this in vertico-multiform. Therefore vertico-multiform should not try to do anything about repairing this.
> 
> I thought about this a bit more. For example you could consider the use case where you enter recursive minibuffers and then turn multiform on and off. This is not a valid operation and it will break since we are already within the around advice `vertico-multiform--advice`. I will add checks and warnings to notify the user about the illegal operation or the inconsistent state. (EDIT: Added in [b5c4e36](https://github.com/minad/vertico/commit/b5c4e3633cbea9540d262e9831e2b0d9887a9841)).

That makes sense.

> About your question above if the two ways are equivalent. They are not! Maybe they are effectively equivalent but you should prefer the second style. The first style has the issue that the quiet mode stays enabled.

Yeah, I realized after posting my comment that the mode layering is still in effect. I've switched to the second style.

**Comment by minad** [comment]
Okay, I decided to call the mode `vertico-unobtrusive-mode`. Please give it a try!

> if: Wrong type argument: overlayp, nil

@karthink Should be fixed in https://github.com/minad/vertico/commit/a53dbfb3c840181af8b71a4e56d043352deb7205

**Comment by karthink** [comment]
There's one more issue with this configuration:

```elisp
(setq vertico-multiform-categories
         '(("" quiet)))

```

If you call a command that has category `nil`, as many commands do, `quiet` (or anything else corresponding to the regexp "") is not applied. This is because of this clause in `vertico-multiform--setup`:

```elisp
(or (vertico-multiform--lookup this-command vertico-multiform-commands)
    (and cat (vertico-multiform--lookup cat vertico-multiform-categories)))
```

If I specify `'(("" quiet))` in `vertico-multiform-commands` instead, then `quiet` is unconditionally applied. So how do I specify `quiet` as the default?

**Comment by minad** [comment]
Good point. Fixed in https://github.com/minad/vertico/commit/1e3450cb676b0cce8989740cee4c84cafa18b369.

**Comment by karthink** [comment]
> Okay, I decided to call the mode `vertico-unobtrusive-mode`. Merged in [5890d09](https://github.com/minad/vertico/commit/5890d09beb7b76457af16ab65ce9d8a8a26d5901). Please give it a try!
> 
> > if: Wrong type argument: overlayp, nil
> 
> @karthink Should be fixed in [a53dbfb](https://github.com/minad/vertico/commit/a53dbfb3c840181af8b71a4e56d043352deb7205)

> Good point. Fixed in 1e3450c.

Tested everything I reported above and more. Looks very good, thank you! I've set it up like MCT/Elmo and don't think I'll be switching back to them for a while.

**Comment by minad** [comment]
> Tested everything I reported above and more. Looks very good, thank you! I've set it up like MCT/Elmo and don't think I'll be switching back to them for a while.

So what would do you miss in comparison to MCT/Elmo? Vertico does not create a real buffer, so you don't have access to the buffer manipulation commands. But the buffer is only an embark-collect-snapshot away which is sufficient for the rare occasions I have to do this.

**Comment by gcv** [comment]
@minad: I wrote this to try to make Tab do what I want:

```emacs-lisp
(defun vertico-smart-tab ()
  (interactive)
  (if (or (not vertico-unobtrusive-mode)
          (= vertico--total 1))
      (call-interactively #'vertico-insert)
    (vertico-multiform-unobtrusive)))

(define-key vertico-map "\t" #'vertico-smart-tab)
```

Configuration:

```emacs-lisp
(setq vertico-multiform-categories
      '((file unobtrusive)
        (buffer flat (vertico-cycle . t))
        (consult-grep buffer)))
```

It seems to work pretty well (at least in the last 10 minutes of testing)! Do you think this is a reasonable approach?

**Comment by minad** [comment]
@gcv Yes, this is a reasonable approach. Note that vertico-flat/unobtrusive prints single matches green with square brackets. This helps for the visual distinction, but I also see some value in your `vertico-smart-tab`.

**Comment by minad** [comment]
@karthink I also added the functionality to switch off enabled modes selectively in https://github.com/minad/vertico/commit/71e15710f05cf40c469fe71ee9c85fc0771d9bba

~~~ elisp
(setq vertico-multiform-commands
      '((execute-extended-command (:not flat indexed))))
~~~

**Comment by gcv** [comment]
@minad: I think I found a bug in the `vertico-multiform-unobtrusive` toggle. Using the configuration I posted above, I see the following:

0. Start with a fresh Emacs session, load Vertico and the configuration.
1. Hit `M-x`, verify that it opens normal Vertico.
2. Hit `C-x C-f`. It opens in unobtrusive mode. Now use `vertico-multiform-unobtrusive`, either with a dedicated key or `vertico-smart-tab`. This toggles out of unobtrusive mode and enables normal Vertico. Now hit `C-g` to exit `find-file`.
3. Hit `M-x` again. It's now unexpectedly in flat mode!

I think this happened in a recent commit because I'm pretty sure it wasn't happening yesterday.

**Comment by gcv** [comment]
After a bit more digging, I found that the bug was introduced in commit ce35812f690b555cdafd5d31d3b5ca157db492b8.

**Comment by phikal** [comment]
@minad I was wondering what you would think about an extensions like 

~~~elisp
(define-minor-mode vertico-disabled-mode
  "Disable vertico."
  :global t :group 'vertico
  (cond
   (vertico-disabled-mode
    (advice-add 'vertico--setup :around #'ignore))
   (t
    (advice-remove 'vertico--setup #'ignore))))
~~~

to disable vertico in combination with multiform mode, when certain commands are better fit for the default completion system, or like you you prefer the defaults, except for some commands where interactive narrowing is preferred, eg.:

~~~elisp
(setq vertico-multiform-commands
      '(("\\`consult-" buffer)
	(t disabled)))
~~~

**Comment by minad** [comment]
@phikal I recently added the `vertico-unobtrusive-mode` which one can use if one wants to disable the verbose Vertico display (but one can still optionally open it). If one wants to use TAB completion, one can bind TAB to `minibuffer-complete` as documented in the README.

I have not spent so much thought about the possibility of mixing different UIs, which I suspect would feel incoherent. In the discussion here we talked about the advantages and disadvantages of Vertico and default-style UIs. The main differentiation is the behavior of TAB completion and the free interaction in the completion buffer. I use Embark if I want free form interaction with the default completion buffer. Or I use this:

~~~ elisp
(defun +vertico-snapshot ()
  "Poor Man's snapshot for Vertico in the style of `embark-collect-snapshot'."
  (interactive)
  (minibuffer-completion-help)
  (run-at-time 0 nil
               (lambda ()
                 (with-current-buffer "*Completions*"
                   (setq-local truncate-lines t)
                   (rename-buffer "*Vertico Snapshot*" 'unique)
                   (pop-to-buffer (current-buffer)))))
  (abort-recursive-edit))
~~~

The vertico-disabled-mode you propose works well. I adjusted it slightly.

~~~ elisp
(define-minor-mode vertico-disabled-mode
  "Disable vertico."
  :global t :group 'vertico
  ;; Shrink current minibuffer window
  (when-let (win (active-minibuffer-window))
    (window-resize win (- (window-pixel-height win)) nil nil 'pixelwise))
  (if vertico-disabled-mode
      (advice-add 'vertico--setup :override #'ignore)
    (advice-remove 'vertico--setup #'ignore)))
~~~

However instead of going that route one should rather extract `vertico-multiform-mode` from Vertico and make it a general recursive minibuffer mode configurator. The code is relatively general, so this may be feasible. On the other hand such a general multiform mode would have to hook into completing read at a certain place and this requires coordination with the UI. I doubt that it is possible to write something which can seamlessly switch between all kinds of UIs across recursive minibuffer sessions, at least it won't be clean and it will be full of package specific hacks.
